# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_bar')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_bar')
    _bar = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bar', [dirname(__file__)])
        except ImportError:
            import _bar
            return _bar
        try:
            _mod = imp.load_module('_bar', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _bar = swig_import_helper()
    del swig_import_helper
else:
    import _bar
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bar.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _bar.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _bar.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _bar.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _bar.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _bar.SwigPyIterator_equal(self, x)

    def copy(self):
        return _bar.SwigPyIterator_copy(self)

    def next(self):
        return _bar.SwigPyIterator_next(self)

    def __next__(self):
        return _bar.SwigPyIterator___next__(self)

    def previous(self):
        return _bar.SwigPyIterator_previous(self)

    def advance(self, n):
        return _bar.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _bar.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _bar.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _bar.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _bar.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _bar.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _bar.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _bar.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vector_foo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_foo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_foo, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _bar.vector_foo_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _bar.vector_foo___nonzero__(self)

    def __bool__(self):
        return _bar.vector_foo___bool__(self)

    def __len__(self):
        return _bar.vector_foo___len__(self)

    def __getslice__(self, i, j):
        return _bar.vector_foo___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _bar.vector_foo___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _bar.vector_foo___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _bar.vector_foo___delitem__(self, *args)

    def __getitem__(self, *args):
        return _bar.vector_foo___getitem__(self, *args)

    def __setitem__(self, *args):
        return _bar.vector_foo___setitem__(self, *args)

    def pop(self):
        return _bar.vector_foo_pop(self)

    def append(self, x):
        return _bar.vector_foo_append(self, x)

    def empty(self):
        return _bar.vector_foo_empty(self)

    def size(self):
        return _bar.vector_foo_size(self)

    def swap(self, v):
        return _bar.vector_foo_swap(self, v)

    def begin(self):
        return _bar.vector_foo_begin(self)

    def end(self):
        return _bar.vector_foo_end(self)

    def rbegin(self):
        return _bar.vector_foo_rbegin(self)

    def rend(self):
        return _bar.vector_foo_rend(self)

    def clear(self):
        return _bar.vector_foo_clear(self)

    def get_allocator(self):
        return _bar.vector_foo_get_allocator(self)

    def pop_back(self):
        return _bar.vector_foo_pop_back(self)

    def erase(self, *args):
        return _bar.vector_foo_erase(self, *args)

    def __init__(self, *args):
        this = _bar.new_vector_foo(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _bar.vector_foo_push_back(self, x)

    def front(self):
        return _bar.vector_foo_front(self)

    def back(self):
        return _bar.vector_foo_back(self)

    def assign(self, n, x):
        return _bar.vector_foo_assign(self, n, x)

    def resize(self, *args):
        return _bar.vector_foo_resize(self, *args)

    def insert(self, *args):
        return _bar.vector_foo_insert(self, *args)

    def reserve(self, n):
        return _bar.vector_foo_reserve(self, n)

    def capacity(self):
        return _bar.vector_foo_capacity(self)
    __swig_destroy__ = _bar.delete_vector_foo
    __del__ = lambda self: None
vector_foo_swigregister = _bar.vector_foo_swigregister
vector_foo_swigregister(vector_foo)

class bar(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bar, name)
    __repr__ = _swig_repr

    def __init__(self, vectors):
        this = _bar.new_bar(vectors)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _bar.delete_bar
    __del__ = lambda self: None

    def get_vectors(self):
        return _bar.bar_get_vectors(self)
    __swig_setmethods__["m_vectors"] = _bar.bar_m_vectors_set
    __swig_getmethods__["m_vectors"] = _bar.bar_m_vectors_get
    if _newclass:
        m_vectors = _swig_property(_bar.bar_m_vectors_get, _bar.bar_m_vectors_set)
bar_swigregister = _bar.bar_swigregister
bar_swigregister(bar)

class foo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, foo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, foo, name)
    __repr__ = _swig_repr

    def __init__(self, x, y, z):
        this = _bar.new_foo(x, y, z)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _bar.delete_foo
    __del__ = lambda self: None
    __swig_setmethods__["m_x"] = _bar.foo_m_x_set
    __swig_getmethods__["m_x"] = _bar.foo_m_x_get
    if _newclass:
        m_x = _swig_property(_bar.foo_m_x_get, _bar.foo_m_x_set)
    __swig_setmethods__["m_y"] = _bar.foo_m_y_set
    __swig_getmethods__["m_y"] = _bar.foo_m_y_get
    if _newclass:
        m_y = _swig_property(_bar.foo_m_y_get, _bar.foo_m_y_set)
    __swig_setmethods__["m_z"] = _bar.foo_m_z_set
    __swig_getmethods__["m_z"] = _bar.foo_m_z_get
    if _newclass:
        m_z = _swig_property(_bar.foo_m_z_get, _bar.foo_m_z_set)

    def mag(self):
        return _bar.foo_mag(self)
foo_swigregister = _bar.foo_swigregister
foo_swigregister(foo)

# This file is compatible with both classic and new-style classes.


