# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_inputModule')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_inputModule')
    _inputModule = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_inputModule', [dirname(__file__)])
        except ImportError:
            import _inputModule
            return _inputModule
        try:
            _mod = imp.load_module('_inputModule', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _inputModule = swig_import_helper()
    del swig_import_helper
else:
    import _inputModule
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _inputModule.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _inputModule.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _inputModule.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _inputModule.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _inputModule.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _inputModule.SwigPyIterator_equal(self, x)

    def copy(self):
        return _inputModule.SwigPyIterator_copy(self)

    def next(self):
        return _inputModule.SwigPyIterator_next(self)

    def __next__(self):
        return _inputModule.SwigPyIterator___next__(self)

    def previous(self):
        return _inputModule.SwigPyIterator_previous(self)

    def advance(self, n):
        return _inputModule.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _inputModule.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _inputModule.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _inputModule.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _inputModule.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _inputModule.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _inputModule.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _inputModule.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class strQueue(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, strQueue, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, strQueue, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _inputModule.new_strQueue(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _inputModule.strQueue_empty(self)

    def size(self):
        return _inputModule.strQueue_size(self)

    def front(self):
        return _inputModule.strQueue_front(self)

    def back(self):
        return _inputModule.strQueue_back(self)

    def pop(self):
        return _inputModule.strQueue_pop(self)

    def push(self, arg2):
        return _inputModule.strQueue_push(self, arg2)
    __swig_destroy__ = _inputModule.delete_strQueue
    __del__ = lambda self: None
strQueue_swigregister = _inputModule.strQueue_swigregister
strQueue_swigregister(strQueue)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _inputModule.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _inputModule.IntVector___nonzero__(self)

    def __bool__(self):
        return _inputModule.IntVector___bool__(self)

    def __len__(self):
        return _inputModule.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _inputModule.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _inputModule.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _inputModule.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _inputModule.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _inputModule.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _inputModule.IntVector___setitem__(self, *args)

    def pop(self):
        return _inputModule.IntVector_pop(self)

    def append(self, x):
        return _inputModule.IntVector_append(self, x)

    def empty(self):
        return _inputModule.IntVector_empty(self)

    def size(self):
        return _inputModule.IntVector_size(self)

    def swap(self, v):
        return _inputModule.IntVector_swap(self, v)

    def begin(self):
        return _inputModule.IntVector_begin(self)

    def end(self):
        return _inputModule.IntVector_end(self)

    def rbegin(self):
        return _inputModule.IntVector_rbegin(self)

    def rend(self):
        return _inputModule.IntVector_rend(self)

    def clear(self):
        return _inputModule.IntVector_clear(self)

    def get_allocator(self):
        return _inputModule.IntVector_get_allocator(self)

    def pop_back(self):
        return _inputModule.IntVector_pop_back(self)

    def erase(self, *args):
        return _inputModule.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _inputModule.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _inputModule.IntVector_push_back(self, x)

    def front(self):
        return _inputModule.IntVector_front(self)

    def back(self):
        return _inputModule.IntVector_back(self)

    def assign(self, n, x):
        return _inputModule.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _inputModule.IntVector_resize(self, *args)

    def insert(self, *args):
        return _inputModule.IntVector_insert(self, *args)

    def reserve(self, n):
        return _inputModule.IntVector_reserve(self, n)

    def capacity(self):
        return _inputModule.IntVector_capacity(self)
    __swig_destroy__ = _inputModule.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _inputModule.IntVector_swigregister
IntVector_swigregister(IntVector)

class inputModule(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, inputModule, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, inputModule, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def fill_q(self, kmers, seq):
        return _inputModule.inputModule_fill_q(self, kmers, seq)

    def setParams(self, params):
        return _inputModule.inputModule_setParams(self, params)
    __swig_destroy__ = _inputModule.delete_inputModule
    __del__ = lambda self: None
inputModule_swigregister = _inputModule.inputModule_swigregister
inputModule_swigregister(inputModule)

class inputModuleDefault(inputModule):
    __swig_setmethods__ = {}
    for _s in [inputModule]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, inputModuleDefault, name, value)
    __swig_getmethods__ = {}
    for _s in [inputModule]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, inputModuleDefault, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _inputModule.new_inputModuleDefault()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def fill_q(self, kmers, seq):
        return _inputModule.inputModuleDefault_fill_q(self, kmers, seq)

    def setParams(self, params):
        return _inputModule.inputModuleDefault_setParams(self, params)
    __swig_destroy__ = _inputModule.delete_inputModuleDefault
    __del__ = lambda self: None
inputModuleDefault_swigregister = _inputModule.inputModuleDefault_swigregister
inputModuleDefault_swigregister(inputModuleDefault)

class InputModuleSkipmers(inputModule):
    __swig_setmethods__ = {}
    for _s in [inputModule]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InputModuleSkipmers, name, value)
    __swig_getmethods__ = {}
    for _s in [inputModule]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InputModuleSkipmers, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _inputModule.new_InputModuleSkipmers()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def fill_q(self, kmers, seq):
        return _inputModule.InputModuleSkipmers_fill_q(self, kmers, seq)

    def setParams(self, parms):
        return _inputModule.InputModuleSkipmers_setParams(self, parms)
    __swig_destroy__ = _inputModule.delete_InputModuleSkipmers
    __del__ = lambda self: None
InputModuleSkipmers_swigregister = _inputModule.InputModuleSkipmers_swigregister
InputModuleSkipmers_swigregister(InputModuleSkipmers)

class moduleFactory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, moduleFactory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, moduleFactory, name)
    __repr__ = _swig_repr
    if _newclass:
        createModule = staticmethod(_inputModule.moduleFactory_createModule)
    else:
        createModule = _inputModule.moduleFactory_createModule

    def __init__(self):
        this = _inputModule.new_moduleFactory()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _inputModule.delete_moduleFactory
    __del__ = lambda self: None
moduleFactory_swigregister = _inputModule.moduleFactory_swigregister
moduleFactory_swigregister(moduleFactory)

def moduleFactory_createModule(mode):
    return _inputModule.moduleFactory_createModule(mode)
moduleFactory_createModule = _inputModule.moduleFactory_createModule

# This file is compatible with both classic and new-style classes.


